CarRental/CarRental/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('accounts/', include('accounts.urls')),
    path('rent/', include('rent.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CarRental/rent/urls.py
from django.urls import path
from . import views

urlpatterns =[
    path('rentcar/<str:pk>/', views.rentcar, name="rentcar"),
    path('successful/<str:pk>/', views.successful, name="successful"),
    path('history/', views.historylist.as_view(), name="history")
]

CarRental/rent/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.conf import settings
from index.models import Car
from datetime import datetime, date

# Create your models here.
class RentCar(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    start = models.DateTimeField()
    end = models.DateTimeField()
    time = models.CharField(max_length=100)
    cost = models.CharField(max_length=10)

    def startdatetime(self):
        print(self)
        return datetime.strptime(str(self.start), '%Y-%m-%dT%H:%M').strftime('%d-%m-%Y %H:%M')
    
    def enddatetime(self):
        return datetime.strptime(str(self.end), '%Y-%m-%dT%H:%M').strftime('%d-%m-%Y %H:%M')

CarRental/rent/views.py
from django.http import request
from .models import RentCar
from django.shortcuts import redirect, render
from index.models import Car
from django.views.generic.list import ListView
from accounts.models import User


# Create your views here.
def successful(request,pk):
    user = request.user
    car = Car.objects.get(id=pk)
    start =  request.POST['startTime']
    end =  request.POST['endTime']
    time =  request.POST['hours']
    cost =  request.POST['cost']
    rentcar = RentCar.objects.create(user=user, car=car, start=start, end=end, time=time, cost=cost)
    rentcar.save()
    return render(request, "rentSuccessful.html", {'rentcar':rentcar})

def rentcar(request, pk):
    car=Car.objects.get(id=pk)
    return render(request, 'rent.html', {'car':car})

class historylist(ListView):
    model=RentCar
    template_name='history.html'
    
    def get_queryset(self):
        return RentCar.objects.filter(user=self.request.user)

CarRental/templates/displaycars.html
{% extends 'main.html' %}

{% block content %}
<div class="hero-wrap ftco-degree-bg" style="background-image: url('../static/images/bg_1.jpg');"
  data-stellar-background-ratio="0.5">
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text justify-content-start align-items-center justify-content-center">
      <div class="col-lg-8 ftco-animate">
        <div class="text w-100 text-center mb-md-5 pb-md-5">
          <h1 class="mb-4">Fast &amp; Easy Way To Rent A Car</h1>
          <p style="font-size: 18px;">A small river named Duden flows by their place and supplies it with the necessary
            regelialia. It is a paradisematic country, in which roasted parts</p>
          <a href="https://vimeo.com/45830194"
            class="icon-wrap popup-vimeo d-flex align-items-center mt-4 justify-content-center">
            <div class="icon d-flex align-items-center justify-content-center">
              <span class="ion-ios-play"></span>
            </div>
            <div class="heading-title ml-5">
              <span>Easy steps for renting a car</span>
            </div>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

<section class="ftco-section ftco-no-pt bg-light">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-12 heading-section text-center ftco-animate mb-5">
        <span class="subheading">What we offer</span>
        <h2 class="mb-2">Featured Vehicles</h2>
      </div>
    </div>
    <div class="row mb-3">
      {% for car in cars %}
      <div class="col-md-6 col-lg-4 mb-4">
          <div class="item">
            <div class="listing d-block  align-items-stretch">
              <div class="listing-img h-100 mr-4">
                <img src="{{car.img.url}}" alt="Image" class="img-fluid">
              </div>
              <div class="listing-contents h-100">
                <h3>{{car.name}}</h3>
                <div class="rent-price">
                  <i class="fa fa-inr" aria-hidden="true"></i><strong> {{car.rent}}</strong><span
                    class="mx-1">/</span>hour
                </div>
                <div class="d-block d-md-flex mb-3 border-bottom pb-3">
                  <div class="listing-feature pr-4">
                    <span class="caption">Luggage: </span><br>
                    <span class="number">{{car.luggage}} bags</span>
                  </div>
                  <div class="listing-feature pr-4">
                    <span class="caption">Doors: </span><br>
                    <span class="number">{{car.door}}</span>
                  </div>
                  <div class="listing-feature pr-4">
                    <span class="caption">Seats: </span><br>
                    <span class="number">{{car.seats}} seats</span>
                  </div>
                </div>
                <div style="text-align: center;">
                  <p><a href="{% url 'rentcar' car.id %}" class="btn btn-primary btn-sm">Rent Now</a></p>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
    </div>
  </div>
</section>



{% endblock %}

CarRental/templates/footer.html
<footer class="ftco-footer ftco-bg-dark ftco-section">
    <div class="container">
      <div class="row mb-5">
        <div class="col-md">
          <div class="ftco-footer-widget mb-4">
            <h2 class="ftco-heading-2"><a href="#" class="logo">Car<span>book</span></a></h2>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
            <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
              <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
              <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
              <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
            </ul>
          </div>
        </div>
        <div class="col-md">
          <div class="ftco-footer-widget mb-4 ml-md-5">
            <h2 class="ftco-heading-2">Information</h2>
            <ul class="list-unstyled">
              <li><a href="#" class="py-2 d-block">About</a></li>
              <li><a href="#" class="py-2 d-block">Services</a></li>
              <li><a href="#" class="py-2 d-block">Term and Conditions</a></li>
              <li><a href="#" class="py-2 d-block">Best Price Guarantee</a></li>
              <li><a href="#" class="py-2 d-block">Privacy &amp; Cookies Policy</a></li>
            </ul>
          </div>
        </div>
        <div class="col-md">
           <div class="ftco-footer-widget mb-4">
            <h2 class="ftco-heading-2">Customer Support</h2>
            <ul class="list-unstyled">
              <li><a href="#" class="py-2 d-block">FAQ</a></li>
              <li><a href="#" class="py-2 d-block">Payment Option</a></li>
              <li><a href="#" class="py-2 d-block">Booking Tips</a></li>
              <li><a href="#" class="py-2 d-block">How it works</a></li>
              <li><a href="#" class="py-2 d-block">Contact Us</a></li>
            </ul>
          </div>
        </div>
        <div class="col-md">
          <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Have a Questions?</h2>
              <div class="block-23 mb-3">
                <ul>
                  <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
                  <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
                  <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
                </ul>
              </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 text-center">

          <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
        </div>
      </div>
    </div>
  </footer>

CarRental/templates/history.html
{% extends 'main.html' %}

{% block content %}
<div style="width: 100%; height:70px; background-color:black"></div>
<div style="margin-top:30px; text-align:center">
    <h1><strong>{{user.name}}</strong> your rental history is:</h1>
    <table border="2" style="width:60%;margin:0 auto;border-collapse:collapse;text-align:center; font-size:18px;">
        <tr style="color: black;">
            <th>Car Name</th>
            <th>Starting Date-Time</th>
            <th>Ending Date-Time</th>
            <th>Total Time</th>
            <th>Total Cost</th>
        </tr>
        {%for rentcar in rentcar_list %}
        <tr>
            <th>{{rentcar.car.name}}</th>
            <th>{{rentcar.start}}</th>
            <th>{{rentcar.end}}</th>
            <th>{{rentcar.time}}</th>
            <th>{{rentcar.cost}}</th>
        </tr>
        {% endfor %}
    </table>
    <h2><strong>Thank You!!!</strong></h2>
{% endblock %}

CarRental/templates/home.html
{% extends 'main.html' %}

{% block content %}
<div class="hero-wrap ftco-degree-bg" style="background-image: url('../static/images/bg_1.jpg');"
  data-stellar-background-ratio="0.5">
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text justify-content-start align-items-center justify-content-center">
      <div class="col-lg-8 ftco-animate">
        <div class="text w-100 text-center mb-md-5 pb-md-5">
          <h1 class="mb-4">Fast &amp; Easy Way To Rent A Car</h1>
          <p style="font-size: 18px;">A small river named Duden flows by their place and supplies it with the necessary
            regelialia. It is a paradisematic country, in which roasted parts</p>
          <a href="https://vimeo.com/45830194"
            class="icon-wrap popup-vimeo d-flex align-items-center mt-4 justify-content-center">
            <div class="icon d-flex align-items-center justify-content-center">
              <span class="ion-ios-play"></span>
            </div>
            <div class="heading-title ml-5">
              <span>Easy steps for renting a car</span>
            </div>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

<section class="ftco-section ftco-no-pt bg-light">
  <div class="container">
    <div class="row no-gutters">
      <div class="col-md-12	featured-top">
        <div class="row" style="margin: 0 auto;">
          <div class="col-md-12 d-flex align-items-center">
            <div class="services-wrap rounded-right w-100">
              <h3 class="heading-section mb-4" style="text-align: center;"><strong>Better Way to Rent Your Perfect Cars</strong></h3>
              <div class="row d-flex mb-4">
                <div class="col-md-4 d-flex align-self-stretch ftco-animate">
                  <div class="services w-100 text-center">
                    <div class="icon d-flex align-items-center justify-content-center"><span
                        class="flaticon-car"></span></div>
                    <div class="text w-100">
                      <h3 class="heading mb-2">Select the Best Car</h3>
                    </div>
                  </div>
                </div>
                <div class="col-md-4 d-flex align-self-stretch ftco-animate">
                  <div class="services w-100 text-center">
                    <div class="icon d-flex align-items-center justify-content-center"><span><i class="fa fa-wpforms"></i></span></div>
                    <div class="text w-100">
                      <h3 class="heading mb-2">Fill Some Details </h3>
                    </div>
                  </div>
                </div>
                <div class="col-md-4 d-flex align-self-stretch ftco-animate">
                  <div class="services w-100 text-center">
                    <div class="icon d-flex align-items-center justify-content-center"><span
                        class="flaticon-rent"></span></div>
                    <div class="text w-100">
                      <h3 class="heading mb-2">Reserve Your Rental Car</h3>
                    </div>
                  </div>
                </div>
              </div >
              <p style="text-align: center"><a href="{% url 'dispcars' %}" class="btn btn-primary py-3 px-4">Reserve Your Perfect Car</a></p>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>


<section class="ftco-section ftco-no-pt bg-light">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-12 heading-section text-center ftco-animate mb-5">
        <span class="subheading">What we offer</span>
        <h2 class="mb-2">Featured Vehicles</h2>
        <a href="{% url 'dispcars' %}" id="viewmore">View More</a>
      </div>
    </div>
    <div class="row">
      
      <div class="col-md-12">
        <div class="carousel-car owl-carousel">
          {% for car in cars %}
          <div class="item">
            <div class="listing d-block  align-items-stretch">
              <div class="listing-img h-100 mr-4">
                <img src="{{car.img.url}}" alt="Image" class="img-fluid">
              </div>
              <div class="listing-contents h-100">
                <h3>{{car.name}}</h3>
                <div class="rent-price">
                  <i class="fa fa-inr" aria-hidden="true"></i><strong> {{car.rent}}</strong><span class="mx-1">/</span>hour
                </div>
                <div class="d-block d-md-flex mb-3 border-bottom pb-3">
                  <div class="listing-feature pr-4">
                    <span class="caption">Luggage: </span><br>
                    <span class="number">{{car.luggage}} bags</span>
                  </div>
                  <div class="listing-feature pr-4">
                    <span class="caption">Doors: </span><br>
                    <span class="number">{{car.door}}</span>
                  </div>
                  <div class="listing-feature pr-4">
                    <span class="caption">Seats: </span><br>
                    <span class="number">{{car.seats}} seats</span>
                  </div>
                </div>
                <div style="text-align: center;">
                  <p><a href="{% url 'rentcar' car.id %}" class="btn btn-primary btn-sm">Rent Now</a></p>
                </div>
              </div>

            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>

<section class="ftco-section ftco-about" id="aboutUs">
  <div class="container">
    <div class="row no-gutters">
      <div class="col-md-6 p-md-5 img img-2 d-flex justify-content-center align-items-center"
        style="background-image: url(images/about.jpg);">
      </div>
      <div class="col-md-6 wrap-about ftco-animate">
        <div class="heading-section heading-section-white pl-md-5">
          <span class="subheading">About us</span>
          <h2 class="mb-4">Welcome to Carbook</h2>

          <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a
            paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
          <p>On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would have
            been rewritten a thousand times and everything that was left from its origin would be the word "and" and the
            Little Blind Text should turn around and return to its own, safe country. A small river named Duden flows by
            their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted
            parts of sentences fly into your mouth.</p>
          <p><a href="#" class="btn btn-primary py-3 px-4">Search Vehicle</a></p>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="ftco-counter ftco-section img bg-light" id="section-counter">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-lg-3 justify-content-center counter-wrap ftco-animate">
        <div class="block-18">
          <div class="text text-border d-flex align-items-center">
            <strong class="number" data-number="60">0</strong>
            <span>Year <br>Experienced</span>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-3 justify-content-center counter-wrap ftco-animate">
        <div class="block-18">
          <div class="text text-border d-flex align-items-center">
            <strong class="number" data-number="1090">0</strong>
            <span>Total <br>Cars</span>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-3 justify-content-center counter-wrap ftco-animate">
        <div class="block-18">
          <div class="text text-border d-flex align-items-center">
            <strong class="number" data-number="2590">0</strong>
            <span>Happy <br>Customers</span>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-3 justify-content-center counter-wrap ftco-animate">
        <div class="block-18">
          <div class="text d-flex align-items-center">
            <strong class="number" data-number="67">0</strong>
            <span>Total <br>Branches</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


{% endblock %}

CarRental/templates/login.html
{% extends 'main.html' %}

{% block content %}

<div class="w3layouts-main">
	<div class="bg-layer">
		<h1>Login</h1>
		<div class="header-main">
			<div class="main-icon">
				<span class="fa fa-sign-in"></span>
			</div>
			<div class="header-left-bottom">
				<form action="{% url 'login' %}" method="post">
					{% csrf_token %}
					<div class="icon1">
						<span class="fa fa-envelope"></span>
						<input type="email" name="email" placeholder="Email Address" style="color:#fff;" required="" />
					</div>
					<div class="icon1">
						<span class="fa fa-lock"></span>
						<input type="password" name="password" placeholder="Password" required="" minlength="8"
							style="color: #fff;" />
					</div>
					<div>
						{% for i in messages %}
						<center><p style="color: red;" >{{i}}</p></center>
						{% endfor %}
					</div>
					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn">
								Login
							</button>
						</div>
					</div>
				</form>
			</div>
		</div>

		<div class="copyright">
			<p>© CARBOOK Login Form. All rights reserved by CARBOOK.</a></p>
		</div>
	</div>
</div>
{% endblock %}

CarRental/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Carbook - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap"
        rel="stylesheet"/>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">


    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" media="all" />
	
</head>

<body>

    {% include 'nav.html' %}

    {% block content %}

    {% endblock %}

    {% include 'footer.html' %}

    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px">
            <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
            <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00" />
        </svg>
    </div>
    
    <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
    <script src="{%static 'js/bootstrap.min.js' %}"></script>
    <script src="{%static 'js/jquery.easing.1.3.js' %}"></script>
    <script src="{%static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{%static 'js/jquery.stellar.min.js' %}"></script>
    <script src="{%static 'js/owl.carousel.min.js' %}"></script>
    <script src="{%static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{%static 'js/aos.js' %}"></script>
    <script src="{%static 'js/jquery.animateNumber.min.js' %}"></script>
    <script src="{%static 'js/bootstrap-datepicker.js' %}"></script>
    <script src="{%static 'js/jquery.timepicker.min.js' %}"></script>
    <script src="{%static 'js/scrollax.min.js' %}"></script>
    <script src="{%static 'js/main.js' %}"></script>
    
</body>

</html>

CarRental/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
  <div class="container">
    <a class="navbar-brand" href="index.html">Car<span>Book</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="oi oi-menu"></span> Menu
    </button>

      <div class="collapse navbar-collapse" id="ftco-nav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active"><a href="{% url 'home' %}" class="nav-link">Home</a></li>
          <!--li class="nav-item"><a href="accounts/register/" class="nav-link">Register</a></li-->
          {% if user.is_authenticated %}
          <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Logout</a></li>
          <li class="nav-item"><a href="{% url 'history' %}" class="nav-link">History</a></li>
          {% else %}
          <li class="nav-item"><a href="{% url 'register' %}" class="nav-link">Register</a></li>
          <li class="nav-item"><a href="{% url 'login' %}" class="nav-link">Login</a></li>
          {% endif %}
          <li class="nav-item"><a href="{% url 'dispcars' %}" class="nav-link">Cars</a></li>
          {% if user.is_authenticated %}
          <li class="nav-item"><span class="username">{{user.name}}</span></li>
          {% endif %}
          
        </ul>
      </div>
    </div>
  </nav>
<script>  
  $(".nav-item").click(function(){
    alert("hi");
    $(this).addClass("active");
  });
</script>

CarRental/templates/registration.html
{% extends 'main.html' %}

{% block content %}

<div class="w3layouts-main">
	<div class="bg-layer">
		<h1>Register</h1>
		<div class="header-main">
			<div class="main-icon">
				<span class="fa fa-sign-in"></span>
			</div>
			<div class="header-left-bottom">
				<form action="{% url 'register' %}" method="post">
					{% csrf_token %}
					<div class="icon1">
						<span class="fa fa-user"></span>
						<input type="text" name="name" placeholder="Full Name" style="color:white" required="" />
					</div>
					<div class="icon1">
						<span class="fa fa-envelope"></span>
						<input type="email" name="email" placeholder="Email Address" style="color:#fff;" required="" />
					</div>
					<div class="icon1">
						<span class="fa fa-phone"></span>
						<input type="tel" name="phone" placeholder="+918923230704" style="color:#fff;" required="" />
					</div>
					<div class="icon1">
						<span class="fa fa-lock"></span>
						<input type="password" name="password1" placeholder="Password" required="" minlength="8"
							style="color: #fff;" />
					</div>
					<div class="icon1">
						<span class="fa fa-lock"></span>
						<input type="password" name="password2" placeholder="Confirm Password" required="" minlength="8"
							style="color: #fff;" />
					</div>
					<div>
						{% for i in messages %}
						<center><p style="color: red;" >{{i}}</p></center>
						{% endfor %}
					</div>
					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn">
								Register
							</button>
						</div>
					</div>
				</form>
			</div>
		</div>

		<div class="copyright">
			<p>© CARBOOK Registration Form. All rights reserved by CARBOOK.</a></p>
		</div>
	</div>
</div>
{% endblock %}

CarRental/templates/rentSuccessful.html
{% extends 'main.html' %}

{% block content %}
<div style="width: 100%; height:70px; background-color:black"></div>
<div style="margin-top:30px; text-align:center">
    <h1>You Have Successfully rented the car <strong>{{rentcar.car.name}}</strong></h1>
    <h2>The details are:</h2>
    <table border="2" style="width:50%;margin:0 auto;border-collapse:collapse;text-align:center; font-size:18px;">
        <tr >
            <th>Username</th>
            <th>{{user.name}}</th>
        </tr>
        <tr>
            <th>Car Name</th>
            <th>{{rentcar.car.name}}</th>
        </tr>
        <tr>
            <th>Starting Date-Time</th>
            <th>{{rentcar.startdatetime}}</th>
        </tr>
        <tr>
            <th>Ending Date-Time</th>
            <th>{{rentcar.enddatetime}}</th>
        </tr>
        <tr>
            <th>Total Time</th>
            <th>{{rentcar.time}}</th>
        </tr>
        <tr>
            <th>Total Cost</th>
            <th>{{rentcar.cost}}</th>
        </tr>
    </table>
    <h2><strong>Thank You!!!</strong></h2>
{% endblock %}